name: tri
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: 3.6.0
  intl: ^0.17.0  
  flutter_animate: ^4.5.0  # Add flutter_animate package for animations
  flutter_spinkit: ^5.1.0 
  font_awesome_flutter: ^10.0.0 # Ensure Firebase core is added for Firebase initialization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/triangle_image.png 
    - assets/profile_picture.png
    