name: tri
description: "A new Flutter project."
publish_to: 'none' # This prevents publishing to pub.dev
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0 # For state management
  cloud_firestore: ^5.4.4 # For Firestore database integration
  firebase_auth: ^5.3.1 # For Firebase authentication
  firebase_core: 3.6.0 # Ensure Firebase core is added for Firebase initialization
  intl: ^0.19.0  # For internationalization and localization
  flutter_animate: ^4.5.0  # Add flutter_animate package for animations
  flutter_spinkit: ^5.1.0  # Loading spinners
  font_awesome_flutter: ^10.0.0  # Icons from Font Awesome
  flutter_svg: ^2.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # For linting and best practices

flutter:
  uses-material-design: true

  assets:
    - assets/triangle_image.png 
    - assets/profile_picture.png
